baseURL: https://gregmakes.xyz/
theme: introduction
googleAnalytics: $GOOGLE_ANALYTICS_MEASUREMENT_ID
DefaultContentLanguage: en
summaryLength: 35
params:
  customCSS: ["style-header-links-like-headers.css"]
  themeStyle: auto
  favicon: /img/favicon.ico
  showRSSButton: false
  fadeIn: false
  fadeInIndex: true
  dateFormat: Jan 2, 2006
  email: greg@gregmakes.xyz
  home:
    introHeight: fullheight
    showLatest: true
    showAllPosts: false
    allPostsArchiveFormat: true
    numberOfProjectsToShow: 3
    localTime: true
    timeZone: America/Denver
    timeFormat: en-US
  projects:
    useTwoColumns: false
  share:
    twitter: true
    facebook: true
    pinterest: true
  social:
    - url: https://linkedin.com/in/gatlp9
      icon: linkedin-in
      icon_pack: fab
    - url: https://github.com/gthoma17
      icon: github
      icon_pack: fab
    - url: mailto:greg@gregmakes.xyz
      icon: paper-plane
      icon_pack: fas
taxonomies:
  tag: tags
  series: series
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: friendly
    tabWidth: 4
languages:
  en:
    languageName: English
    languageCode: en-us
    weight: 0
    title: Greg Thomas -- Technologist & Solution Finder
    menu:
      main:
      - identifier:  about-me
        name: "About Me"
        url: "/"
        weight: 1
      - identifier:  resume
        name: "Résumé"
        url: "/static/resumes/forwarder.html"
        weight: 10
      - identifier:  projects
        name: "Projects"
        url: "/projects"
        weight: 60
      - identifier:  blog
        name: "Blog"
        url: "/blog"
        weight: 90
      - identifier:  jp
        name: "日本語"
        url: "/jp"
        weight: 100
  jp:
    languageName: 日本語
    languageCode: jp
    weight: 1
    title: はじめまして
    menu:
      main:
      - identifier:  about-me-jp
        name: "私について"
        url: "/jp"
        weight: 100
      - identifier:  english
        name: "ENGLISH"
        url: "/"
        weight: 0
