baseUrl = "/"
theme = "slick"
title = "Greg Thomas"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
canonifyURLs = true

# Configure pagination
paginate = 10
paginatePath = "page"

[params]
    subtitle = "Technologist & Solution Finder"
    description = "The personal website of Greg Thomas, Technologist & Solution Finder."
    favicon = "images/favicon.ico"
    images = "/images/profile-pic.jpg"
    css = "styles/site.css" # TODO create inside static or assets folder
    dateFmt = "Jan 2, 2006"
    errorPageText = "There's nothing to see here, please try a different page."
    showRssLink = true
    showFullContent = false
    showEmptyPagination = false
    showMeta = true
    showMetaDates = true
    showMetaLinks = true
    noteDateFmt = "2006-01-02@3:04pm" 
    noteProfilePic = "/images/wpap-profile-pic.gif"

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true               # Allow html (needed for some shortcodes)
    [markup.highlight]
        codeFences = true               # Enable highlighting inside codefences
        guessSyntax = true              # Highlight code without language tag
        noClasses = false               # Use the theme's style sheet

# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"
    categories = "categories"
    series = "series"


[author]
    name = "Greg Thomas"
    email = "Greg@GregMakes.xyz"
    picture = "/images/profile-pic.jpg"
    nickname = "Greg"
    h_card_url = "https://gregmakes.xyz"
    url = "gregmakes.xyz"
    locality = "Denver"
    region = "Colorado"
    country_name = "USA"
    bday = "20 Mar 1993"
    gender_identity = "non-binary"


[services.rss]
    limit = 0 # unlimited


[menu]
    [[menu.main]]
        name = "All Posts"
        url = "/posts/"
        weight = 100

    [[menu.main]]
        name = "Notes"
        url = "/notes"
        weight = 200

    [[menu.main]]
        name = "Résumé"
        url = "/documents/resume/"
        weight = 999

    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    [[menu.meta]]
        identifier = "categories"
        name = "Categories"
        weight = 1
    [[menu.meta]]
        identifier = "series"
        name = "Series"
        weight = 2
    [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 3


    # Add some footer links to your likings
    [[menu.footer]]
        name = "Github"
        url = "https://github.com/gthoma17"
        pre = "rel=me"
        weight = 100
    [[menu.footer]]
        name = "Linkedin"
        url = "https://linkedin.com/in/gatlp9"
        weight = 200
    
[sitemap]
  filename = "sitemap.xml"
  # Values are 'always', 'hourly', 'daily',' weekly', 'monthly', 'yearly', and 'never'. 
  # Set to empty string to omit inclusion
  changefreq = "always"
  # Values range from 0.0 to 1.0. 
  # Set to -1 to omit inclusion
  priority =  1
