baseUrl = "https://gregmakes.xyz"
title = "Greg Thomas"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
canonifyURLs = true

# Configure pagination
paginate = 10
paginatePath = "page"

[params]
    subtitle = "Technologist & Solution Finder"
    description = "The personal website of Greg Thomas, Technologist & Solution Finder."
    favicon = "images/favicon.ico"
    css = "styles/site.css" # TODO create inside static or assets folder
    dateFmt = "Jan 2, 2006"
    errorPageText = "There's nothing to see here, please try a different page."
    noteDateFmt = "2006-01-02@3:04pm" 
    deploymentUrl = "https://gregmakes.xyz/"
    webmentionUrl = "https://gregmakes.xyz/linkback/webmention"
    pingbackUrl = "https://gregmakes.xyz/linkback/pingback"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true               # Allow html (needed for some shortcodes)
    [markup.highlight]
        codeFences = true               # Enable highlighting inside codefences
        guessSyntax = true              # Highlight code without language tag
        noClasses = false               # Use the theme's style sheet

    [markup.tableOfContents]
        endLevel = 4
        ordered = false
        startLevel = 1

# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"
    categories = "categories"
    series = "series"


[author]
    name = "Greg Thomas"
    email = "Greg@GregMakes.xyz"
    picture = "http://gregmakes.xyz/images/profile-pic.jpg"
    profile_picture = "http://gregmakes.xyz/images/wpap-profile-pic.gif"
    nickname = "Greg"
    h_card_url = "https://gregmakes.xyz"
    url = "gregmakes.xyz"
    locality = "Denver"
    region = "Colorado"
    country_name = "USA"
    bday = "20 Mar 1993"
    gender_identity = "non-binary"


[services.rss]
    limit = 0 # unlimited


[menu]
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 100

    [[menu.main]]
        name = "Notes"
        url = "/notes"
        weight = 200

    [[menu.main]]
        name = "Résumé"
        url = "/documents/resume/"
        weight = 999

    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    [[menu.meta]]
        identifier = "categories"
        name = "Categories"
        weight = 1
    [[menu.meta]]
        identifier = "series"
        name = "Series"
        weight = 2
    [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 3

    [[menu.footer]]
        name = "Github"
        url = "https://github.com/gthoma17"
        pre = "rel=me"
        weight = 100

    [[menu.footer]]
        name = "Linkedin"
        url = "https://linkedin.com/in/gatlp9"
        weight = 200

    [[menu.footer]]
        name = "RSS"
        url = "/index.xml"
        weight = 300

    [[menu.footer]]
        name = "Sitemap"
        url = "/sitemap.xml"
        weight = 400

    [[menu.footer]]
        name = "Privacy Policy"
        url = "/privacy_policy/"
        weight = 999
    
[sitemap]
  filename = "sitemap.xml"
  changefreq = "always" # 'always', 'hourly', 'daily',' weekly', 'monthly', 'yearly', 'never' or '' (to omit inclusion)  
  priority =  1 # Values range from 0.0 to 1.0. Set to -1 to omit inclusion

