name: Build Static Site
on: [push]
jobs:
  Build-Static-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.84.3"

      - name: Check out repository code
        uses: actions/checkout@v2

#      - name: Update theme
#        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
#        run: git submodule update --init --recursive

      - run: make deploy
