name: Build Static Site
on: [push]
jobs:
  Deploy-Site:
    runs-on: ubuntu-latest
    steps:

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.84.3"

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - run: make deploy
