name: Build Static Site
on:
  push:
    branches:
      - "*"
jobs:
  Build-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'astro_site/package-lock.json'

      - name: Install dependencies
        run: cd astro_site && npm ci

      - name: Build
        run: make build
        env:
          WEBMENTIONS_URL: ${{ secrets.WEBMENTIONS_URL }}

  Deploy-Site:
    runs-on: ubuntu-latest
    needs: Build-Site
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'astro_site/package-lock.json'

      - name: Install dependencies
        run: cd astro_site && npm ci

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy
        run: make deploy
        env:
          WEBMENTIONS_URL: ${{ secrets.WEBMENTIONS_URL }}

      - name: Send Webmentions
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.WEBMENTIONS_URL }}
          method: PUT

      - name: Commit New Webmentions
        env:
          WEBMENTIONS_URL: ${{ secrets.WEBMENTIONS_URL }}
        run: |
          sleep 1 # Give go-jamming a second to process new mentions
          make get-webmentions
          if [[ `git status --porcelain` ]]; then
            git add **/webmentions.json
            git status
            git config user.name "GitHub Actions"
            git config user.email "<>"

            git commit -m "Save new webmentions"
            git push origin main
          fi
          exit 0
        shell: bash
