name: Build Static Site
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
jobs:
  Build-Site:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'astro_site/package-lock.json'

      - name: Install dependencies
        run: cd astro_site && npm ci

      - name: Install ImageMagick for HEIC conversion
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Run microformats tests
        run: cd astro_site && npm run test:microformats

      - name: Build
        run: make build
        env:
          WEBMENTIONS_URL: ${{ secrets.WEBMENTIONS_URL }}

  Deploy-Site:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'astro_site/package-lock.json'

      - name: Install dependencies
        run: cd astro_site && npm ci

      - name: Install ImageMagick for HEIC conversion
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Run microformats tests
        run: cd astro_site && npm run test:microformats

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy
        run: make deploy
        env:
          WEBMENTIONS_URL: ${{ secrets.WEBMENTIONS_URL }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

#      - name: Send Webmentions
#        uses: satak/webrequest-action@master
#        with:
#          url: ${{ secrets.WEBMENTIONS_URL }}
#          method: PUT

#      - name: Commit New Webmentions
#        env:
#          WEBMENTIONS_URL: ${{ secrets.WEBMENTIONS_URL }}
#        run: |
#          sleep 1 # Give go-jamming a second to process new mentions
#          make get-webmentions
#          if [[ `git status --porcelain` ]]; then
#            git add **/webmentions.json
#            git status
#            git config user.name "GitHub Actions"
#            git config user.email "<>"

#            git commit -m "Save new webmentions"
#            git push origin main
#          fi
#          exit 0
#        shell: bash
